name: Sync logos to S3 bucket
on:
  push:
    workflow_dispatch:
    branches:
      - main
env:
  AWS_REGION: us-east-2
  S3_BUCKET: odigos-destinations
jobs:
  sync-logos:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/odigos-ci
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync logos
        run: |
          aws s3 sync destinations/logos/ s3://${{ env.S3_BUCKET }}/ --delete
